steps:

# Set a persistent volume according to https://cloud.google.com/cloud-build/docs/build-config (search for volumes)
- name: 'ubuntu'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: ['cp', '-a', '.', '/persistent_volume']

# using flutter builder Docker image we have built previously to compile the repo
- name: 'gcr.io/cloud-builders/docker'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: ['run', '-v', 'vol1:/home/app', '--rm', 'gcr.io/$PROJECT_ID/flutter', '--cache-from' ,'-c', 'cd /home/app && flutter build apk --debug']

# Push the APK Output from vol1 to your GCS Bucket with Short Commit SHA.
- name: 'gcr.io/cloud-builders/gsutil'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: ['cp', '/persistent_volume/build/app/outputs/flutter-apk/app-debug.apk', '/persistent_volume/integration_test/appium-flutter-driver-example/']

# using flutter builder Docker image we have built previously to compile the repo
- name: 'gcr.io/cloud-builders/docker'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  entrypoint: ['bash']
  args: ['run', '-v', 'vol1:/app', '--rm', 'gcr.io/$PROJECT_ID/ubuntu:master', '--cache-from', 'c', 'cd /app && ./docker/start.sh']


timeout: 3200s