on:
  push:
    branches:
      - 'appium-flutter-driver'

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        
      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      
      - name: Clone Tests
        uses: actions/checkout@master
        with:
          repository: FerreiraJo/appium-flutter-driver-example
          token: ${{ secrets.ACCESS_TOKEN }}
          path: appium-flutter-driver-example
      
      - name: Flutter cache
        uses: actions/cache@v2
        id: flutter
        with:
          path: |
            ~/hostedtoolcache/flutter
            ~/.pub-cache
          key: flutter

      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.1'
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
      - run: flutter build apk --debug
      
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ls
      
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install -g appium@1.22.1 --allow-root --unsafe-perm=true
      - run: npm install -g appium-flutter-driver --allow-root --unsafe-perm=true

      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          # cache: 'npm'
          # cache-dependency-path: subdir/package-lock.json
      - run: cd /appium-flutter-driver-example
      - run: bundle install
      - run: bundle exec rake tasks
